// Copyright 2020 Hewlett Packard Enterprise Development LP
package model


/**
 * <p>Golang package for NsObjectType Enum.</p>
 */

type NsObjectType string 

const (
	NSOBJECTTYPE_ARRAY_NETCONFIG NsObjectType = "array_netconfig"
	NSOBJECTTYPE_USER_POLICY NsObjectType = "user_policy"
	NSOBJECTTYPE_SUBNET NsObjectType = "subnet"
	NSOBJECTTYPE_ENCRYPT_KEY NsObjectType = "encrypt_key"
	NSOBJECTTYPE_INITIATOR NsObjectType = "initiator"
	NSOBJECTTYPE_KEYMANAGER NsObjectType = "keymanager"
	NSOBJECTTYPE_NIC NsObjectType = "nic"
	NSOBJECTTYPE_BRANCH NsObjectType = "branch"
	NSOBJECTTYPE_FC_TARGET_PORT_GROUP NsObjectType = "fc_target_port_group"
	NSOBJECTTYPE_PROTTMPL NsObjectType = "prottmpl"
	NSOBJECTTYPE_PROTPOL NsObjectType = "protpol"
	NSOBJECTTYPE_SSHKEY NsObjectType = "sshkey"
	NSOBJECTTYPE_FC_INTERFACE_COLLECTION NsObjectType = "fc_interface_collection"
	NSOBJECTTYPE_VOLCOLL NsObjectType = "volcoll"
	NSOBJECTTYPE_INITIATORGRP_SUBNET NsObjectType = "initiatorgrp_subnet"
	NSOBJECTTYPE_PE_ACL NsObjectType = "pe_acl"
	NSOBJECTTYPE_VVOL_ACL NsObjectType = "vvol_acl"
	NSOBJECTTYPE_CHAPUSER NsObjectType = "chapuser"
	NSOBJECTTYPE_EVENTS NsObjectType = "events"
	NSOBJECTTYPE_APPLICATION_SERVER NsObjectType = "application_server"
	NSOBJECTTYPE_GROUP NsObjectType = "group"
	NSOBJECTTYPE_POOL NsObjectType = "pool"
	NSOBJECTTYPE_VVOL NsObjectType = "vvol"
	NSOBJECTTYPE_ACTIVE_DIRECTORY NsObjectType = "active_directory"
	NSOBJECTTYPE_SHELF NsObjectType = "shelf"
	NSOBJECTTYPE_DISK NsObjectType = "disk"
	NSOBJECTTYPE_ROUTE NsObjectType = "route"
	NSOBJECTTYPE_FOLDER NsObjectType = "folder"
	NSOBJECTTYPE_IP_ADDRESS NsObjectType = "ip address"
	NSOBJECTTYPE_FC NsObjectType = "fc"
	NSOBJECTTYPE_SUPPORT NsObjectType = "support"
	NSOBJECTTYPE_SNAPSHOT NsObjectType = "snapshot"
	NSOBJECTTYPE_THROTTLE NsObjectType = "throttle"
	NSOBJECTTYPE_ROLE NsObjectType = "role"
	NSOBJECTTYPE_SNAPCOLL NsObjectType = "snapcoll"
	NSOBJECTTYPE_SESSION NsObjectType = "session"
	NSOBJECTTYPE_ASYNC_JOB NsObjectType = "async_job"
	NSOBJECTTYPE_INITIATORGRP NsObjectType = "initiatorgrp"
	NSOBJECTTYPE_PERFPOLICY NsObjectType = "perfpolicy"
	NSOBJECTTYPE_PRIVILEGE NsObjectType = "privilege"
	NSOBJECTTYPE_SYSLOG NsObjectType = "syslog"
	NSOBJECTTYPE_USER_GROUP NsObjectType = "user group"
	NSOBJECTTYPE_PROTSCHED NsObjectType = "protsched"
	NSOBJECTTYPE_NETCONFIG NsObjectType = "netconfig"
	NSOBJECTTYPE_VOL NsObjectType = "vol"
	NSOBJECTTYPE_FC_INITIATOR_ALIAS NsObjectType = "fc_initiator_alias"
	NSOBJECTTYPE_ARRAY NsObjectType = "array"
	NSOBJECTTYPE_ALARM NsObjectType = "alarm"
	NSOBJECTTYPE_FC_PORT NsObjectType = "fc_port"
	NSOBJECTTYPE_PROTOCOL_ENDPOINT NsObjectType = "protocol_endpoint"
	NSOBJECTTYPE_FOLSET NsObjectType = "folset"
	NSOBJECTTYPE_AUDIT_LOG NsObjectType = "audit_log"
	NSOBJECTTYPE_HC_CLUSTER_CONFIG NsObjectType = "hc_cluster_config"
	NSOBJECTTYPE_ENCRYPT_CONFIG NsObjectType = "encrypt_config"
	NSOBJECTTYPE_WITNESS NsObjectType = "witness"
	NSOBJECTTYPE_PARTNER NsObjectType = "partner"
	NSOBJECTTYPE_SNAPSHOT_LUN NsObjectType = "snapshot_lun"
	NSOBJECTTYPE_EVENT_DIPATCHER NsObjectType = "event_dipatcher"
	NSOBJECTTYPE_VOLACL NsObjectType = "volacl"
	NSOBJECTTYPE_USER NsObjectType = "user"

) 
