// Copyright 2020 Hewlett Packard Enterprise Development LP
package model

// Golang package for NsPlatFcOperationalStatus Enum.

type NsPlatFcOperationalStatus string

const (
	cNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline NsPlatFcOperationalStatus = "plat_fc_operational_status_admin_offline"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusDirect       NsPlatFcOperationalStatus = "plat_fc_operational_status_direct"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing NsPlatFcOperationalStatus = "plat_fc_operational_status_initializing"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured   NsPlatFcOperationalStatus = "plat_fc_operational_status_configured"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusFault        NsPlatFcOperationalStatus = "plat_fc_operational_status_fault"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusOperational  NsPlatFcOperationalStatus = "plat_fc_operational_status_operational"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown      NsPlatFcOperationalStatus = "plat_fc_operational_status_unknown"
	cNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured NsPlatFcOperationalStatus = "plat_fc_operational_status_unconfigured"
)

var pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusFault NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured NsPlatFcOperationalStatus

// Export
var NsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusDirect *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusInitializing *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusConfigured *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusFault *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusOperational *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusUnknown *NsPlatFcOperationalStatus
var NsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured *NsPlatFcOperationalStatus

func init() {
	pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline = cNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline
	NsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline = &pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline

	pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect = cNsPlatFcOperationalStatusPlatFcOperationalStatusDirect
	NsPlatFcOperationalStatusPlatFcOperationalStatusDirect = &pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect

	pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing = cNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing
	NsPlatFcOperationalStatusPlatFcOperationalStatusInitializing = &pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing

	pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured = cNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured
	NsPlatFcOperationalStatusPlatFcOperationalStatusConfigured = &pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured

	pNsPlatFcOperationalStatusPlatFcOperationalStatusFault = cNsPlatFcOperationalStatusPlatFcOperationalStatusFault
	NsPlatFcOperationalStatusPlatFcOperationalStatusFault = &pNsPlatFcOperationalStatusPlatFcOperationalStatusFault

	pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational = cNsPlatFcOperationalStatusPlatFcOperationalStatusOperational
	NsPlatFcOperationalStatusPlatFcOperationalStatusOperational = &pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational

	pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown = cNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown
	NsPlatFcOperationalStatusPlatFcOperationalStatusUnknown = &pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown

	pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured = cNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured
	NsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured = &pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured

}
