// Copyright 2020 Hewlett Packard Enterprise Development LP
package model

// Golang package for NsSynchronousReplicationState Enum.

type NsSynchronousReplicationState string

const (
	cNsSynchronousReplicationStateInSync        NsSynchronousReplicationState = "in_sync"
	cNsSynchronousReplicationStateNotApplicable NsSynchronousReplicationState = "not_applicable"
	cNsSynchronousReplicationStateOutOfSync     NsSynchronousReplicationState = "out_of_sync"
	cNsSynchronousReplicationStateUnknown       NsSynchronousReplicationState = "unknown"
)

var pNsSynchronousReplicationStateInSync NsSynchronousReplicationState
var pNsSynchronousReplicationStateNotApplicable NsSynchronousReplicationState
var pNsSynchronousReplicationStateOutOfSync NsSynchronousReplicationState
var pNsSynchronousReplicationStateUnknown NsSynchronousReplicationState

// Export
var NsSynchronousReplicationStateInSync *NsSynchronousReplicationState
var NsSynchronousReplicationStateNotApplicable *NsSynchronousReplicationState
var NsSynchronousReplicationStateOutOfSync *NsSynchronousReplicationState
var NsSynchronousReplicationStateUnknown *NsSynchronousReplicationState

func init() {
	pNsSynchronousReplicationStateInSync = cNsSynchronousReplicationStateInSync
	NsSynchronousReplicationStateInSync = &pNsSynchronousReplicationStateInSync

	pNsSynchronousReplicationStateNotApplicable = cNsSynchronousReplicationStateNotApplicable
	NsSynchronousReplicationStateNotApplicable = &pNsSynchronousReplicationStateNotApplicable

	pNsSynchronousReplicationStateOutOfSync = cNsSynchronousReplicationStateOutOfSync
	NsSynchronousReplicationStateOutOfSync = &pNsSynchronousReplicationStateOutOfSync

	pNsSynchronousReplicationStateUnknown = cNsSynchronousReplicationStateUnknown
	NsSynchronousReplicationStateUnknown = &pNsSynchronousReplicationStateUnknown

}
