// Copyright 2020 Hewlett Packard Enterprise Development LP
package model

// Golang package for NsTemperatureStatus Enum.

type NsTemperatureStatus string

const (
	cNsTemperatureStatusTemperatureUnknown NsTemperatureStatus = "temperature_unknown"
	cNsTemperatureStatusTemperatureAlerted NsTemperatureStatus = "temperature_alerted"
	cNsTemperatureStatusTemperatureOkay    NsTemperatureStatus = "temperature_okay"
	cNsTemperatureStatusTemperatureFail    NsTemperatureStatus = "temperature_fail"
)

var pNsTemperatureStatusTemperatureUnknown NsTemperatureStatus
var pNsTemperatureStatusTemperatureAlerted NsTemperatureStatus
var pNsTemperatureStatusTemperatureOkay NsTemperatureStatus
var pNsTemperatureStatusTemperatureFail NsTemperatureStatus

// Export
var NsTemperatureStatusTemperatureUnknown *NsTemperatureStatus
var NsTemperatureStatusTemperatureAlerted *NsTemperatureStatus
var NsTemperatureStatusTemperatureOkay *NsTemperatureStatus
var NsTemperatureStatusTemperatureFail *NsTemperatureStatus

func init() {
	pNsTemperatureStatusTemperatureUnknown = cNsTemperatureStatusTemperatureUnknown
	NsTemperatureStatusTemperatureUnknown = &pNsTemperatureStatusTemperatureUnknown

	pNsTemperatureStatusTemperatureAlerted = cNsTemperatureStatusTemperatureAlerted
	NsTemperatureStatusTemperatureAlerted = &pNsTemperatureStatusTemperatureAlerted

	pNsTemperatureStatusTemperatureOkay = cNsTemperatureStatusTemperatureOkay
	NsTemperatureStatusTemperatureOkay = &pNsTemperatureStatusTemperatureOkay

	pNsTemperatureStatusTemperatureFail = cNsTemperatureStatusTemperatureFail
	NsTemperatureStatusTemperatureFail = &pNsTemperatureStatusTemperatureFail

}
