<<<<<<< HEAD
// Copyright 2020 Hewlett Packard Enterprise Development LP

package nimbleos


=======
// Copyright 2021 Hewlett Packard Enterprise Development LP

package nimbleos

>>>>>>> 87138d62 (Add autogenerated files)
// NsAuthenticateChapUserReturn - Response of chap user authentication.
// Export NsAuthenticateChapUserReturnFields for advance operations like search filter etc.
var NsAuthenticateChapUserReturnFields *NsAuthenticateChapUserReturn

<<<<<<< HEAD
func init(){

 NsAuthenticateChapUserReturnFields= &NsAuthenticateChapUserReturn{
 }
}


type NsAuthenticateChapUserReturn struct {
 // IsValid - Chap user secret is valid.
    IsValid *bool `json:"is_valid,omitempty"`
=======
func init() {

	NsAuthenticateChapUserReturnFields = &NsAuthenticateChapUserReturn{}
}

type NsAuthenticateChapUserReturn struct {
	// IsValid - Chap user secret is valid.
	IsValid *bool `json:"is_valid,omitempty"`
>>>>>>> 87138d62 (Add autogenerated files)
}
