<<<<<<< HEAD
// Copyright 2020 Hewlett Packard Enterprise Development LP
=======
// Copyright 2021 Hewlett Packard Enterprise Development LP
>>>>>>> 87138d62 (Add autogenerated files)
package nimbleos

// Golang package for NsOTPType Enum.

type NsOTPType string

const (
<<<<<<< HEAD
 cNsOTPTypeGoogleAuth NsOTPType = "google_auth"
 cNsOTPTypeNone NsOTPType = "none"
=======
	cNsOTPTypeGoogleAuth NsOTPType = "google_auth"
	cNsOTPTypeNone       NsOTPType = "none"
>>>>>>> 87138d62 (Add autogenerated files)
)

var pNsOTPTypeGoogleAuth NsOTPType
var pNsOTPTypeNone NsOTPType

// NsOTPTypeGoogleAuth enum exports
var NsOTPTypeGoogleAuth *NsOTPType

// NsOTPTypeNone enum exports
var NsOTPTypeNone *NsOTPType

func init() {
<<<<<<< HEAD
 pNsOTPTypeGoogleAuth = cNsOTPTypeGoogleAuth
 NsOTPTypeGoogleAuth = &pNsOTPTypeGoogleAuth

 pNsOTPTypeNone = cNsOTPTypeNone
 NsOTPTypeNone = &pNsOTPTypeNone

}

=======
	pNsOTPTypeGoogleAuth = cNsOTPTypeGoogleAuth
	NsOTPTypeGoogleAuth = &pNsOTPTypeGoogleAuth

	pNsOTPTypeNone = cNsOTPTypeNone
	NsOTPTypeNone = &pNsOTPTypeNone

}
>>>>>>> 87138d62 (Add autogenerated files)
