// Copyright 2020 Hewlett Packard Enterprise Development LP
package nimbleos

// Golang package for NsPlatFcOperationalStatus Enum.

type NsPlatFcOperationalStatus string

const (
 cNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline NsPlatFcOperationalStatus = "plat_fc_operational_status_admin_offline"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusDirect NsPlatFcOperationalStatus = "plat_fc_operational_status_direct"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing NsPlatFcOperationalStatus = "plat_fc_operational_status_initializing"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured NsPlatFcOperationalStatus = "plat_fc_operational_status_configured"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusFault NsPlatFcOperationalStatus = "plat_fc_operational_status_fault"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusOperational NsPlatFcOperationalStatus = "plat_fc_operational_status_operational"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown NsPlatFcOperationalStatus = "plat_fc_operational_status_unknown"
 cNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured NsPlatFcOperationalStatus = "plat_fc_operational_status_unconfigured"
)

var pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusFault NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown NsPlatFcOperationalStatus
var pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusDirect enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusDirect *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusInitializing enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusInitializing *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusConfigured enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusConfigured *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusFault enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusFault *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusOperational enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusOperational *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusUnknown enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusUnknown *NsPlatFcOperationalStatus

// NsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured enum exports
var NsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured *NsPlatFcOperationalStatus

func init() {
 pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline = cNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline
 NsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline = &pNsPlatFcOperationalStatusPlatFcOperationalStatusAdminOffline

 pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect = cNsPlatFcOperationalStatusPlatFcOperationalStatusDirect
 NsPlatFcOperationalStatusPlatFcOperationalStatusDirect = &pNsPlatFcOperationalStatusPlatFcOperationalStatusDirect

 pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing = cNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing
 NsPlatFcOperationalStatusPlatFcOperationalStatusInitializing = &pNsPlatFcOperationalStatusPlatFcOperationalStatusInitializing

 pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured = cNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured
 NsPlatFcOperationalStatusPlatFcOperationalStatusConfigured = &pNsPlatFcOperationalStatusPlatFcOperationalStatusConfigured

 pNsPlatFcOperationalStatusPlatFcOperationalStatusFault = cNsPlatFcOperationalStatusPlatFcOperationalStatusFault
 NsPlatFcOperationalStatusPlatFcOperationalStatusFault = &pNsPlatFcOperationalStatusPlatFcOperationalStatusFault

 pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational = cNsPlatFcOperationalStatusPlatFcOperationalStatusOperational
 NsPlatFcOperationalStatusPlatFcOperationalStatusOperational = &pNsPlatFcOperationalStatusPlatFcOperationalStatusOperational

 pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown = cNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown
 NsPlatFcOperationalStatusPlatFcOperationalStatusUnknown = &pNsPlatFcOperationalStatusPlatFcOperationalStatusUnknown

 pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured = cNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured
 NsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured = &pNsPlatFcOperationalStatusPlatFcOperationalStatusUnconfigured

}

